# Generated by Django 5.0.6 on 2024-06-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Centro_Adopcion', '0002_dogs_foto_alter_cats_age_alter_cats_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cats',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_mascotas'),
        ),
    ]
