# Generated by Django 5.0.6 on 2024-06-21 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Centro_Adopcion', '0003_cats_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adopted_pet',
            options={'verbose_name': 'Adopted Pet', 'verbose_name_plural': 'Adopted Pets'},
        ),
        migrations.AlterModelOptions(
            name='cats',
            options={'verbose_name': 'Cat', 'verbose_name_plural': 'Cats'},
        ),
        migrations.AlterModelOptions(
            name='dogs',
            options={'verbose_name': 'Dog', 'verbose_name_plural': 'Dogs'},
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avatar',
                'verbose_name_plural': 'Avatars',
            },
        ),
    ]
